spring:
  application:
    name: ${SPRING_APPLICATION_NAME:fdelivery-order-service}
  webflux:
    basePath: /fdelivery-order-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/cart-item
    username: root
    password: root
  data:
    mongodb:
      host: mongodb_container
      port: 27017
      database: fdelivery-order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: rhd-order-exchange
    queue: rhd-order-queue
    routing-key: rhd-order-routingkey


management:
  server:
    port: 9089
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    jp:
      rhd:
        cart: TRACE
    org:
      springframework:
        data:
          r2dbc: DEBUG
      zalando:
        logbook: TRACE

server:
  port: 8089

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
    - ${server.servlet.contextPath}/webjars/**
    - ${server.servlet.contextPath}/v2/api-docs/**
    - ${server.servlet.contextPath}/swagger-ui.html/**
    - ${server.servlet.contextPath}/swagger-resources/**
  filter.enabled: true
  format.style: splunk
  strategy: default
  obfuscate:
    parameters:
      - access_token
      - password
      - token

app:
  jwtSecret: secret

client:
  driver:
    get-all-drivers: http://fdelivery-driver-service:8088/fdelivery-driver-service